/**
 * Notion-style avatars — one chosen index per part layer, stacked as
 * absolutely-positioned SVGs in a square. Parts live in
 * `public/notion-avatar/part/{layer}/{layer}-{n}.svg` (MIT, ported from
 * Mayandev/notion-avatar); `src/data/avatarManifest.ts` (generated by
 * `scripts/build-avatar-manifest.mjs`) records each part's crop rect on the
 * shared 1080x1080 canvas so layers line up instead of stretching to fill
 * the square independently.
 *
 * Every account gets a default before it ever picks anything: `deterministicAvatar`
 * hashes the handle into the same config every time, so two people never need
 * to coordinate to get different-looking defaults, and a returning user's
 * avatar does not shuffle on reload.
 */

export const AVATAR_LAYER_ORDER = [
  'face',
  'nose',
  'mouth',
  'eyes',
  'eyebrows',
  'glasses',
  'hair',
  'accessories',
  'details',
  'beard',
] as const

export type AvatarLayer = (typeof AVATAR_LAYER_ORDER)[number]

/** File counts per layer folder (indices are 0-based, exclusive upper bound). */
export const AVATAR_PART_COUNTS: Record<AvatarLayer, number> = {
  face: 16,
  nose: 14,
  mouth: 20,
  eyes: 14,
  eyebrows: 16,
  glasses: 15,
  hair: 59,
  accessories: 15,
  details: 14,
  beard: 17,
}

/** Curated pastel backgrounds — the Notion picker's palette, not the app's category accents. */
export const AVATAR_BACKGROUNDS = [
  '#F4F4EF',
  '#FDE7C8',
  '#FBD4D4',
  '#E4E1FB',
  '#DCEEFB',
  '#DCEFE3',
  '#FBE7F3',
  '#F0E6D6',
] as const

export type AvatarPartsConfig = Record<AvatarLayer, number> & { bg: string }
export type ImageAvatarConfig = { type: 'image'; url: string }
export type AvatarConfig = AvatarPartsConfig | ImageAvatarConfig

export function isImageAvatar(
  config: AvatarConfig | null | undefined,
): config is ImageAvatarConfig {
  return Boolean(config) && (config as ImageAvatarConfig).type === 'image'
}

export function isPartsAvatar(
  config: AvatarConfig | null | undefined,
): config is AvatarPartsConfig {
  return Boolean(config) && !isImageAvatar(config)
}

export function partSrc(layer: AvatarLayer, index: number): string {
  const count = AVATAR_PART_COUNTS[layer]
  const safe = ((index % count) + count) % count
  return `/notion-avatar/part/${layer}/${layer}-${safe}.svg`
}

/** FNV-1a — small, dependency-free, stable across runs and platforms. */
function fnv1a(seed: string): number {
  let hash = 0x811c9dc5
  for (let i = 0; i < seed.length; i += 1) {
    hash ^= seed.charCodeAt(i)
    hash = Math.imul(hash, 0x01000193)
  }
  return hash >>> 0
}

/** mulberry32 — deterministic PRNG so every layer draws an independent value from one seed. */
function mulberry32(seed: number) {
  let state = seed
  return () => {
    state = (state + 0x6d2b79f5) | 0
    let t = Math.imul(state ^ (state >>> 15), 1 | state)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/**
 * Same seed, same avatar, every time — this is what a handle resolves to
 * before anyone has opened the picker.
 */
export function deterministicAvatar(seed: string): AvatarPartsConfig {
  const draw = mulberry32(fnv1a(seed.trim().toUpperCase() || 'OBOLUS'))
  const config = {} as AvatarPartsConfig
  for (const layer of AVATAR_LAYER_ORDER) {
    config[layer] = Math.floor(draw() * AVATAR_PART_COUNTS[layer])
  }
  config.bg = AVATAR_BACKGROUNDS[Math.floor(draw() * AVATAR_BACKGROUNDS.length)]
  return config
}

/** The "randomize" button — a fresh, unrepeatable seed. */
export function randomAvatar(): AvatarPartsConfig {
  return deterministicAvatar(`${Date.now().toString(36)}_${Math.random().toString(36).slice(2)}`)
}

/* ------------------------------------------------------ image upload mode */

/**
 * The whole avatar rides inside the profile POST body as a data URL (this is a
 * devnet demo with no object storage — the image lives on the profile row).
 * The Rust API caps the ENTIRE request body at 64 KiB
 * (`DefaultBodyLimit::max(64 * 1024)` in backend/src/lib.rs), so an avatar data
 * URL near or above that ceiling fails the profile save with HTTP 413 before
 * the handler runs at all. Keep the encoded data URL comfortably under it,
 * leaving headroom for the rest of the profile JSON, so uploads never 413.
 */
export const AVATAR_IMAGE_MAX_DATA_URL_BYTES = 56 * 1024
const AVATAR_IMAGE_TARGET_PX = 256

function readAsImage(file: File): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => {
      const img = new Image()
      img.onload = () => resolve(img)
      img.onerror = () => reject(new Error('That file is not a readable image.'))
      img.src = reader.result as string
    }
    reader.onerror = () => reject(new Error('That file could not be read.'))
    reader.readAsDataURL(file)
  })
}

/**
 * Crop to a centered square, downscale, and re-encode until the data URL
 * fits the storage budget — this is a devnet demo with no object storage, so
 * the whole image lives as a data URL on the profile row.
 */
export async function fileToSquareDataUrl(
  file: File,
  targetPx = AVATAR_IMAGE_TARGET_PX,
): Promise<string> {
  if (!file.type.startsWith('image/')) {
    throw new Error('Choose an image file.')
  }
  const img = await readAsImage(file)
  const canvas = document.createElement('canvas')
  canvas.width = targetPx
  canvas.height = targetPx
  const ctx = canvas.getContext('2d')
  if (!ctx) throw new Error('This browser cannot resize images.')
  const side = Math.min(img.width, img.height)
  const sx = (img.width - side) / 2
  const sy = (img.height - side) / 2
  ctx.drawImage(img, sx, sy, side, side, 0, 0, targetPx, targetPx)

  // `dataUrl.length` is the encoded size that actually rides in the request
  // body, so compare against the budget directly — drop quality until it fits.
  let quality = 0.9
  let dataUrl = canvas.toDataURL('image/jpeg', quality)
  while (dataUrl.length > AVATAR_IMAGE_MAX_DATA_URL_BYTES && quality > 0.3) {
    quality -= 0.15
    dataUrl = canvas.toDataURL('image/jpeg', quality)
  }
  if (dataUrl.length > AVATAR_IMAGE_MAX_DATA_URL_BYTES) {
    throw new Error('That image is still too large after compression. Try a simpler photo.')
  }
  return dataUrl
}
