use crate::domain::Document;

#[allow(clippy::too_many_arguments)]
fn document(
    id: &str,
    handle: &str,
    author_id: &str,
    shelf_id: &str,
    shelf: &str,
    category: &str,
    content: &str,
    tags: &[&str],
    price_krw: u64,
    age_days: u32,
) -> Document {
    Document {
        id: id.to_owned(),
        handle: handle.to_owned(),
        author_id: author_id.to_owned(),
        shelf_id: shelf_id.to_owned(),
        shelf: shelf.to_owned(),
        category: category.to_owned(),
        content: content.to_owned(),
        tags: tags.iter().map(|tag| (*tag).to_owned()).collect(),
        price_krw,
        age_days,
        quality_score: 0.9,
        reliability_score: 0.9,
        locked: false,
        demographics: None,
    }
}

/// Demo corpus only. Production storage will replace this without changing the
/// resolver or its payment-safe response contract.
pub fn documents() -> Vec<Document> {
    vec![
        document(
            "md_seongsu_11",
            "SEONGS_11",
            "author_101",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "I eat lunch inside Seongsu almost every day, but once the wait goes past 30 minutes I just grab a convenience store lunchbox.",
            &["Seongsu", "weekday lunch", "queue", "resident"],
            10,
            4,
        ),
        document(
            "md_seongsu_12",
            "SEONGS_12",
            "author_102",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "Yeonmujang-gil is unwalkable after 2pm on a weekend, so I do the grocery run before 10am on Saturday.",
            &["Seongsu", "daily route", "weekend", "resident"],
            10,
            12,
        ),
        document(
            "md_seongsu_13",
            "SEONGS_13",
            "author_103",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "The stairs at Seongsu Station exit 3 are narrow, so at rush hour I walk one stop and board at Kondae-ipgu.",
            &["Seongsu", "commute", "daily route", "resident"],
            10,
            24,
        ),
        document(
            "md_seongsu_14",
            "SEONGS_14",
            "author_104",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "Plenty of cafes, nowhere to sit and work for long. I rotate between the two that have outlets.",
            &["Seongsu", "cafe", "work", "resident"],
            10,
            8,
        ),
        document(
            "md_seongsu_15",
            "SEONGS_15",
            "author_105",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "The laundry by my place shuts at 8pm, so all my shirts go in together on Wednesday morning before the weekday lunch crowd arrives.",
            &["Seongsu", "laundry", "weekday", "resident"],
            10,
            17,
        ),
        document(
            "md_seongsu_16",
            "SEONGS_16",
            "author_106",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "Rent is nine hundred fifty thousand won with maintenance included, and in summer the air conditioning adds about one hundred twenty thousand won.",
            &["Seongsu", "rent", "daily cost", "resident"],
            10,
            27,
        ),
        document(
            "md_seongsu_ko1",
            "SEONGS_KO1",
            "author_107",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "성수동에서 평일 점심을 먹습니다. 12시 전에 가면 줄이 없고, 12시 반이면 20분 기다립니다.",
            &["Seongsu", "weekday lunch", "queue", "resident"],
            10,
            5,
        ),
        document(
            "md_seongsu_ko2",
            "SEONGS_KO2",
            "author_108",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "성수역 근처 국숫집은 포장이 빠릅니다. 자리는 좁아서 혼자 갈 때만 갑니다.",
            &["Seongsu", "noodles", "takeout", "resident"],
            10,
            19,
        ),
        document(
            "md_lunch_11",
            "WEEKDA_11",
            "author_201",
            "weekday-lunch",
            "Weekday office lunch",
            "F&B",
            "Ten thousand won is my line for lunch. If a place goes over it, I do a convenience store run once that week.",
            &["weekday lunch", "office", "price", "queue"],
            5,
            6,
        ),
        document(
            "md_lunch_12",
            "WEEKDA_12",
            "author_202",
            "weekday-lunch",
            "Weekday office lunch",
            "F&B",
            "Leave at 12 sharp and everywhere is a 20-minute wait, so our team agreed to head out at 11:50.",
            &["weekday lunch", "office", "queue", "wait"],
            5,
            18,
        ),
        document(
            "md_paris_11",
            "PARISR_11",
            "author_301",
            "paris-resident",
            "Five years in Paris",
            "Travel",
            "I do the weekly shop on Sunday morning at the market. By noon the good produce is gone and the aisles are packed.",
            &["Paris", "resident", "daily route", "shopping"],
            15,
            5,
        ),
        document(
            "md_paris_12",
            "PARISR_12",
            "author_302",
            "paris-resident",
            "Five years in Paris",
            "Travel",
            "I eat out maybe twice a month. The lunch set is eighteen euros and dinner is double that, so dinner happens at home.",
            &["Paris", "resident", "dinner", "daily life"],
            15,
            15,
        ),
        document(
            "md_paris_13",
            "PARISR_13",
            "author_303",
            "paris-resident",
            "Five years in Paris",
            "Travel",
            "Half the shops on my street close in August. Anyone visiting then, I warn them in advance.",
            &["Paris", "resident", "August", "daily life"],
            15,
            33,
        ),
        document(
            "md_cafe_11",
            "INDIEC_11",
            "author_401",
            "indie-cafe-owner",
            "Running a small cafe",
            "F&B",
            "I go through 12kg of beans a month. I changed suppliers twice, and the one I use now is twenty-two thousand won per kg.",
            &["cafe owner", "beans", "supplier", "cost"],
            25,
            3,
        ),
        document(
            "md_cafe_12",
            "INDIEC_12",
            "author_402",
            "indie-cafe-owner",
            "Running a small cafe",
            "F&B",
            "Opening at 7am brings in about 20 people on their way to work, and nearly all buy one americano.",
            &["cafe owner", "sales", "opening hours", "margin"],
            25,
            14,
        ),
        document(
            "md_backend_11",
            "BACKEN_11",
            "author_501",
            "backend-dev-3y",
            "Backend devs, year three",
            "Hiring & Roles",
            "The first production pager rotation was harder than writing the service. I spent two months turning tribal runbooks into alerts the whole team could follow.",
            &["backend engineer", "pager", "production", "small team"],
            20,
            9,
        ),
        document(
            "md_backend_12",
            "BACKEN_12",
            "author_502",
            "backend-dev-3y",
            "Backend devs, year three",
            "Hiring & Roles",
            "A managed database migration cut the monthly bill, but the rollback plan and connection pool caused most of the work.",
            &[
                "backend engineer",
                "database migration",
                "cost",
                "production",
            ],
            20,
            21,
        ),
        document(
            "md_wallet_11",
            "ONCHAI_11",
            "author_601",
            "onchain-wallet",
            "Everyday onchain wallets",
            "Crypto & Investing",
            "I split across three wallets: one for spending, one for storage, and one for contracts I have never seen before.",
            &["Solana", "wallet", "onchain", "security"],
            20,
            7,
        ),
        document(
            "md_wallet_12",
            "ONCHAI_12",
            "author_602",
            "onchain-wallet",
            "Everyday onchain wallets",
            "Crypto & Investing",
            "Fees on Solana are cheap, so small payments go through there and I keep a separate spending wallet.",
            &["Solana", "wallet", "micropayment", "fees"],
            20,
            11,
        ),
        document(
            "md_kolunch_1",
            "KOLUNCH_1",
            "author_203",
            "seongsu-lunch-ko",
            "성수동에서 먹고 삽니다",
            "life",
            "성수동 사무실에서 일하는 직장인입니다. 평일 점심은 회사 앞 백반집에서 8천원짜리 정식을 먹습니다. 12시 정각에 가면 자리가 없어서 11시 50분에 나갑니다.",
            &["성수동", "직장인", "평일 점심", "백반집"],
            10,
            4,
        ),
        document(
            "md_kolunch_2",
            "KOLUNCH_2",
            "author_204",
            "seongsu-lunch-ko",
            "성수동에서 먹고 삽니다",
            "life",
            "성수동 IT 거리에서 근무하는 직장인입니다. 평일 점심시간이 짧아서 회사에서 도보 5분 거리의 국숫집만 갑니다. 한 그릇에 9천원이고 15분이면 다 먹고 나옵니다.",
            &["성수동", "직장인", "평일 점심", "국수"],
            10,
            9,
        ),
        document(
            "md_kolunch_3",
            "KOLUNCH_3",
            "author_205",
            "seongsu-lunch-ko",
            "성수동에서 먹고 삽니다",
            "life",
            "성수동 스타트업에서 일하는 직장인입니다. 평일 점심값을 아끼려고 일주일에 3번은 회사 구내식당에서 6천원짜리 식사를 합니다. 나머지 2번은 팀원들과 밖에서 만원짜리 메뉴를 먹습니다.",
            &["성수동", "직장인", "평일 점심", "구내식당"],
            10,
            13,
        ),
        document(
            "md_kolunch_4",
            "KOLUNCH_4",
            "author_206",
            "seongsu-lunch-ko",
            "성수동에서 먹고 삽니다",
            "life",
            "성수동 사무실에서 3년째 출근하는 직장인입니다. 평일 점심은 카페 브런치로 해결할 때가 많은데 한 끼에 1만 2천원 정도 듭니다. 자리가 없으면 포장해서 사무실에서 먹습니다.",
            &["성수동", "직장인", "평일 점심", "브런치"],
            10,
            20,
        ),
        document(
            "md_kolunch_5",
            "KOLUNCH_5",
            "author_207",
            "seongsu-lunch-ko",
            "성수동에서 먹고 삽니다",
            "life",
            "성수동 공유오피스에서 근무하는 직장인입니다. 평일 점심은 근처 분식집에서 떡볶이랑 김밥 세트로 7천원에 해결합니다. 줄이 길면 10분만 기다리고 다른 곳으로 갑니다.",
            &["성수동", "직장인", "평일 점심", "분식"],
            10,
            28,
        ),
        // Sensitivity note: this doc (and to a lesser extent KOPARIS_4/KOPARIS_5) is the
        // marginal candidate that keeps `search::tests::insufficient_coverage_preserves_
        // existing_quote_and_only_fills_gap` (an English-only query about Paris residents'
        // "daily routes and dinner habits") passing. That query shares only "paris"/"dinner"
        // with this shelf (via search.rs's Korean->English canonical bridge), so relevance for
        // it hovers close to MIN_RELEVANCE (0.22) — as measured, this doc currently sits at
        // ~0.28, and is the ONLY one of the 5 KOPARIS_* docs that still clears the bar (the
        // test needs total eligible candidates for that query to stay below 5; it's currently
        // exactly 4 = the 3 pre-existing PARISR_* docs + this one). Adding more shared
        // vocabulary with "저녁"/"파리" here, or trimming this doc's Korean-only filler text,
        // can tip a second KOPARIS_* doc over 0.22 and flip that test from Miss to Hit.
        document(
            "md_koparis_1",
            "KOPARIS_1",
            "author_208",
            "paris-dinner-ko",
            "파리에 삽니다",
            "travel",
            "파리에서 5년째 살고 있습니다. 평일 저녁은 실제로 퇴근하고 근처 골목 시장에 들러 제철 채소와 자투리 고기를 사서 집에서 소박하게 한 끼를 차려 먹는 날이 많은데, 그렇게 장을 보면 재료비로 한 끼에 8유로 정도 씁니다. 외식은 한 달에 딱 두 번 정도만 합니다.",
            &["평일", "자취", "골목시장", "장보기습관"],
            15,
            6,
        ),
        document(
            "md_koparis_2",
            "KOPARIS_2",
            "author_209",
            "paris-dinner-ko",
            "파리에 삽니다",
            "travel",
            "파리 근교에서 살고 있는 직장인입니다. 평일 저녁 식사는 실제로 대부분 파스타나 샐러드로 간단히 차립니다. 장보기는 일주일에 한 번, 20유로어치를 삽니다.",
            &["평일", "직장인", "장보기", "간단식사"],
            15,
            10,
        ),
        document(
            "md_koparis_3",
            "KOPARIS_3",
            "author_210",
            "paris-dinner-ko",
            "파리에 삽니다",
            "travel",
            "파리에서 유학생으로 산 지 2년째입니다. 평일 저녁은 실제로 기숙사 공용 주방에서 직접 차려 먹습니다. 재료비가 하루 5유로를 넘지 않게 관리합니다.",
            &["평일", "유학", "기숙사", "재료비"],
            15,
            15,
        ),
        document(
            "md_koparis_4",
            "KOPARIS_4",
            "author_211",
            "paris-dinner-ko",
            "파리에 삽니다",
            "travel",
            "파리에서 3년째 살고 있습니다. 평일 저녁 메뉴는 냉장고에 남은 자잘한 재료로 대충 만드는 편인데, 실제로 일부러 배달을 시키는 날은 한 달에 한 번 정도이고 가격은 15유로 선입니다.",
            &["평일", "집밥", "냉장고정리", "가격"],
            15,
            21,
        ),
        document(
            "md_koparis_5",
            "KOPARIS_5",
            "author_212",
            "paris-dinner-ko",
            "파리에 삽니다",
            "travel",
            "파리 시내에서 일하고 근교 조용한 주택가에서 삽니다. 평일 저녁에 뭘 먹나요 하면, 저는 실제로 퇴근길에 골목 안 오래된 동네 단골 빵집에 들러 갓 구운 바게트와 치즈 한 조각을 사 오는 날이 많다고 답합니다. 집에서 간단히 차려 먹는데 한 끼에 6유로쯤 듭니다.",
            &["평일", "퇴근길", "동네빵집", "주택가생활"],
            15,
            29,
        ),
        document(
            "md_koschool_1",
            "KOSCHOOL_1",
            "author_213",
            "first-grade-ko",
            "초등 입학 준비",
            "family",
            "초등학교 입학 준비를 시작했습니다. 책가방과 실내화 같은 준비물에 15만원 정도 썼습니다. 방과후 돌봄 신청비로 3만원을 추가로 냈습니다.",
            &["초등학교", "입학", "준비물", "학비"],
            20,
            5,
        ),
        document(
            "md_koschool_2",
            "KOSCHOOL_2",
            "author_214",
            "first-grade-ko",
            "초등 입학 준비",
            "family",
            "초등학교 입학 준비 중입니다. 학원 대신 학습지를 선택했는데 한 달에 4만원이 나갑니다. 신발주머니와 명찰 같은 자잘한 준비물에도 2만원 넘게 들었습니다.",
            &["초등학교", "입학", "학습지", "준비물"],
            20,
            8,
        ),
        document(
            "md_koschool_3",
            "KOSCHOOL_3",
            "author_215",
            "first-grade-ko",
            "초등 입학 준비",
            "family",
            "초등학교 입학 전 두 달 동안 가장 돈이 많이 드는 건 교복이 아니었습니다. 방과후 미술학원비가 한 달에 8만원씩 나갔습니다.",
            &["초등학교", "입학", "방과후", "학원비"],
            20,
            14,
        ),
        document(
            "md_koschool_4",
            "KOSCHOOL_4",
            "author_216",
            "first-grade-ko",
            "초등 입학 준비",
            "family",
            "초등학교 입학 준비물 목록을 다 채웠습니다. 총 20만원 가까이 썼는데 절반은 문구가 아니라 정장 구두와 가방값이었습니다.",
            &["초등학교", "입학", "준비물", "비용"],
            20,
            19,
        ),
        document(
            "md_koschool_5",
            "KOSCHOOL_5",
            "author_217",
            "first-grade-ko",
            "초등 입학 준비",
            "family",
            "초등학교 입학 앞두고 비용을 알아봤습니다. 돈이 제일 많이 드는 건 태권도장 종일반이었습니다. 한 달에 35만원이라 결국 학교 돌봄교실로 바꿨습니다.",
            &["초등학교", "입학", "돌봄교실", "학원비"],
            20,
            25,
        ),
        // 패딩 문서 6건(INDIEC_13/14, BACKEN_13/14, ONCHAI_13/14)은 검색의 앵커 컷오프
        // (search.rs의 rare_cutoff = 문서수/5, 현재 40건→8)를 안정시키기 위한 것.
        // 시드를 지우거나 추가하면 컷오프와 용어 빈도가 바뀌어 모든 질문의 HIT 결과가
        // 조용히 달라질 수 있으니, 시드 증감 시 데모 질문 4종 스모크를 다시 돌릴 것.
        document(
            "md_kocafe_1",
            "INDIEC_13",
            "author_218",
            "indie-cafe-owner",
            "Running a small cafe",
            "F&B",
            "작은 카페를 5년째 운영하고 있습니다. 원두 로스팅을 직접 배운 뒤로 재료비를 20% 줄였고, 단골손님은 한 달에 150명 정도 됩니다.",
            &["카페", "로스팅", "원가", "단골"],
            25,
            6,
        ),
        document(
            "md_kocafe_2",
            "INDIEC_14",
            "author_219",
            "indie-cafe-owner",
            "Running a small cafe",
            "F&B",
            "동네에서 작은 카페를 운영합니다. 디저트 메뉴를 새로 추가한 뒤 매출이 늘어서 하루 평균 손님이 40명에서 60명으로 늘었습니다.",
            &["카페", "디저트", "매출", "단골"],
            25,
            12,
        ),
        document(
            "md_koback_1",
            "BACKEN_13",
            "author_220",
            "backend-dev-3y",
            "Backend devs, year three",
            "Hiring & Roles",
            "백엔드 개발자로 3년째 일하고 있습니다. 장애 대응 문서를 정리한 뒤로 야간 호출이 한 달에 2번으로 줄었습니다.",
            &["백엔드", "장애대응", "야간호출", "문서화"],
            20,
            8,
        ),
        document(
            "md_koback_2",
            "BACKEN_14",
            "author_221",
            "backend-dev-3y",
            "Backend devs, year three",
            "Hiring & Roles",
            "3년차 서버 개발자입니다. 데이터베이스 마이그레이션을 직접 진행했는데 준비 기간만 6주가 걸렸습니다.",
            &["백엔드", "데이터베이스", "마이그레이션", "일정"],
            20,
            16,
        ),
        document(
            "md_kowallet_1",
            "ONCHAI_13",
            "author_222",
            "onchain-wallet",
            "Everyday onchain wallets",
            "Crypto & Investing",
            "온체인 지갑을 세 개로 나눠 씁니다. 콜드월렛에는 자산의 80%를 보관하고 나머지는 소액 결제용으로 씁니다.",
            &["온체인", "지갑", "콜드월렛", "보안"],
            20,
            10,
        ),
        document(
            "md_kowallet_2",
            "ONCHAI_14",
            "author_223",
            "onchain-wallet",
            "Everyday onchain wallets",
            "Crypto & Investing",
            "지갑 시드 문구는 종이에 적어서 금고에 보관합니다. 거래소에는 필요한 만큼만 남기고 나머지는 매주 한 번씩 옮깁니다.",
            &["온체인", "지갑", "시드문구", "보안"],
            20,
            17,
        ),
    ]
}
