use crate::domain::Document;

#[allow(clippy::too_many_arguments)]
fn document(
    id: &str,
    handle: &str,
    author_id: &str,
    shelf_id: &str,
    shelf: &str,
    category: &str,
    content: &str,
    tags: &[&str],
    price_krw: u64,
    age_days: u32,
) -> Document {
    Document {
        id: id.to_owned(),
        handle: handle.to_owned(),
        author_id: author_id.to_owned(),
        shelf_id: shelf_id.to_owned(),
        shelf: shelf.to_owned(),
        category: category.to_owned(),
        content: content.to_owned(),
        tags: tags.iter().map(|tag| (*tag).to_owned()).collect(),
        price_krw,
        age_days,
        quality_score: 0.9,
        reliability_score: 0.9,
        locked: false,
        demographics: None,
    }
}

/// Demo corpus only. Production storage will replace this without changing the
/// resolver or its payment-safe response contract.
pub fn documents() -> Vec<Document> {
    vec![
        document(
            "md_seongsu_11",
            "SEONGS_11",
            "author_101",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "I eat lunch inside Seongsu almost every day, but once the wait goes past 30 minutes I just grab a convenience store lunchbox.",
            &["Seongsu", "weekday lunch", "queue", "resident"],
            420,
            4,
        ),
        document(
            "md_seongsu_12",
            "SEONGS_12",
            "author_102",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "Yeonmujang-gil is unwalkable after 2pm on a weekend, so I do the grocery run before 10am on Saturday.",
            &["Seongsu", "daily route", "weekend", "resident"],
            420,
            12,
        ),
        document(
            "md_seongsu_13",
            "SEONGS_13",
            "author_103",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "The stairs at Seongsu Station exit 3 are narrow, so at rush hour I walk one stop and board at Kondae-ipgu.",
            &["Seongsu", "commute", "daily route", "resident"],
            420,
            24,
        ),
        document(
            "md_seongsu_14",
            "SEONGS_14",
            "author_104",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "Plenty of cafes, nowhere to sit and work for long. I rotate between the two that have outlets.",
            &["Seongsu", "cafe", "work", "resident"],
            420,
            8,
        ),
        document(
            "md_seongsu_15",
            "SEONGS_15",
            "author_105",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "The laundry by my place shuts at 8pm, so all my shirts go in together on Wednesday morning before the weekday lunch crowd arrives.",
            &["Seongsu", "laundry", "weekday", "resident"],
            420,
            17,
        ),
        document(
            "md_seongsu_16",
            "SEONGS_16",
            "author_106",
            "seongsu-living",
            "Living in Seongsu",
            "Neighborhood",
            "Rent is nine hundred fifty thousand won with maintenance included, and in summer the air conditioning adds about one hundred twenty thousand won.",
            &["Seongsu", "rent", "daily cost", "resident"],
            420,
            27,
        ),
        document(
            "md_lunch_11",
            "WEEKDA_11",
            "author_201",
            "weekday-lunch",
            "Weekday office lunch",
            "F&B",
            "Ten thousand won is my line for lunch. If a place goes over it, I do a convenience store run once that week.",
            &["weekday lunch", "office", "price", "queue"],
            260,
            6,
        ),
        document(
            "md_lunch_12",
            "WEEKDA_12",
            "author_202",
            "weekday-lunch",
            "Weekday office lunch",
            "F&B",
            "Leave at 12 sharp and everywhere is a 20-minute wait, so our team agreed to head out at 11:50.",
            &["weekday lunch", "office", "queue", "wait"],
            260,
            18,
        ),
        document(
            "md_paris_11",
            "PARISR_11",
            "author_301",
            "paris-resident",
            "Five years in Paris",
            "Travel",
            "I do the weekly shop on Sunday morning at the market. By noon the good produce is gone and the aisles are packed.",
            &["Paris", "resident", "daily route", "shopping"],
            820,
            5,
        ),
        document(
            "md_paris_12",
            "PARISR_12",
            "author_302",
            "paris-resident",
            "Five years in Paris",
            "Travel",
            "I eat out maybe twice a month. The lunch set is eighteen euros and dinner is double that, so dinner happens at home.",
            &["Paris", "resident", "dinner", "daily life"],
            820,
            15,
        ),
        document(
            "md_paris_13",
            "PARISR_13",
            "author_303",
            "paris-resident",
            "Five years in Paris",
            "Travel",
            "Half the shops on my street close in August. Anyone visiting then, I warn them in advance.",
            &["Paris", "resident", "August", "daily life"],
            820,
            33,
        ),
        document(
            "md_cafe_11",
            "INDIEC_11",
            "author_401",
            "indie-cafe-owner",
            "Running a small cafe",
            "F&B",
            "I go through 12kg of beans a month. I changed suppliers twice, and the one I use now is twenty-two thousand won per kg.",
            &["cafe owner", "beans", "supplier", "cost"],
            1_250,
            3,
        ),
        document(
            "md_cafe_12",
            "INDIEC_12",
            "author_402",
            "indie-cafe-owner",
            "Running a small cafe",
            "F&B",
            "Opening at 7am brings in about 20 people on their way to work, and nearly all buy one americano.",
            &["cafe owner", "sales", "opening hours", "margin"],
            1_250,
            14,
        ),
        document(
            "md_backend_11",
            "BACKEN_11",
            "author_501",
            "backend-dev-3y",
            "Backend devs, year three",
            "Hiring & Roles",
            "The first production pager rotation was harder than writing the service. I spent two months turning tribal runbooks into alerts the whole team could follow.",
            &["backend engineer", "pager", "production", "small team"],
            1_100,
            9,
        ),
        document(
            "md_backend_12",
            "BACKEN_12",
            "author_502",
            "backend-dev-3y",
            "Backend devs, year three",
            "Hiring & Roles",
            "A managed database migration cut the monthly bill, but the rollback plan and connection pool caused most of the work.",
            &[
                "backend engineer",
                "database migration",
                "cost",
                "production",
            ],
            1_100,
            21,
        ),
        document(
            "md_wallet_11",
            "ONCHAI_11",
            "author_601",
            "onchain-wallet",
            "Everyday onchain wallets",
            "Crypto & Investing",
            "I split across three wallets: one for spending, one for storage, and one for contracts I have never seen before.",
            &["Solana", "wallet", "onchain", "security"],
            1_150,
            7,
        ),
        document(
            "md_wallet_12",
            "ONCHAI_12",
            "author_602",
            "onchain-wallet",
            "Everyday onchain wallets",
            "Crypto & Investing",
            "Fees on Solana are cheap, so small payments go through there and I keep a separate spending wallet.",
            &["Solana", "wallet", "micropayment", "fees"],
            1_150,
            11,
        ),
    ]
}
