substitutions:
  _REGION: asia-northeast3
  _REPOSITORY: obolus
  _TAG: manual

timeout: 2400s

steps:
  - id: api
    name: gcr.io/cloud-builders/docker
    waitFor: ['-']
    args:
      - build
      - --file
      - backend/Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api:${_TAG}
      - backend

  - id: browser-gateway
    name: gcr.io/cloud-builders/docker
    waitFor: ['-']
    args:
      - build
      - --file
      - payment-gateway/Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/gateway:${_TAG}
      - payment-gateway

  - id: orchestrator
    name: gcr.io/cloud-builders/docker
    waitFor: ['-']
    args:
      - build
      - --file
      - agent-orchestrator/Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/orchestrator:${_TAG}
      - agent-orchestrator

  - id: pay-sh
    name: gcr.io/cloud-builders/docker
    waitFor: ['-']
    args:
      - build
      - --file
      - pay/Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/pay:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/gateway:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/orchestrator:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/pay:${_TAG}
